In [ ]:
import pandas as pd
import numpy as np

from tqdm import tqdm  # Importa tqdm para mostrar la barra de progreso
from pprint import pprint

import matplotlib.pyplot as plt
import seaborn as sns

# Normalizacion
from sklearn.preprocessing import MinMaxScaler
import warnings
warnings.filterwarnings('ignore')

# SQL
import mysql.connector

In [2]:
df_places = pd.read_csv("geoplaces2.csv")
df_accepts = pd.read_csv("chefmozaccepts.csv")
df_cuisine = pd.read_csv("chefmozcuisine.csv")
df_hours = pd.read_csv("chefmozhours4.csv")
df_parking = pd.read_csv("chefmozparking.csv")
df_rating_final = pd.read_csv("rating_final.csv")

In [3]:
df_places

,placeID,latitude,longitude,the_geom_meter,name,address,city,state,country,fax,...,alcohol,smoking_area,dress_code,accessibility,price,url,Rambience,franchise,area,other_services
0,134999,18.915421,-99.184871,0101000020957F000088568DE356715AC138C0A525FC46...,Kiku Cuernavaca,Revolucion,Cuernavaca,Morelos,Mexico,?,...,No_Alcohol_Served,none,informal,no_accessibility,medium,kikucuernavaca.com.mx,familiar,f,closed,none
1,132825,22.147392,-100.983092,0101000020957F00001AD016568C4858C1243261274BA5...,puesto de tacos,esquina santos degollado y leon guzman,s.l.p.,s.l.p.,mexico,?,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,f,open,none
2,135106,22.149709,-100.976093,0101000020957F0000649D6F21634858C119AE9BF528A3...,El Rincï¿½n de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,?,...,Wine-Beer,only at bar,informal,partially,medium,?,familiar,f,open,none
3,132667,23.752697,-99.163359,0101000020957F00005D67BCDDED8157C1222A2DC8D84D...,little pizza Emilio Portes Gil,calle emilio portes gil,victoria,tamaulipas,?,?,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,t,closed,none
4,132613,23.752903,-99.165076,0101000020957F00008EBA2D06DC8157C194E03B7B504E...,carnitas_mata,lic. Emilio portes gil,victoria,Tamaulipas,Mexico,?,...,No_Alcohol_Served,permitted,informal,completely,medium,?,familiar,t,closed,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,132866,22.141220,-100.931311,0101000020957F000013871838EC4A58C1B5DF74F8E396...,Chaires,Ricardo B. Anaya,San Luis Potosi,San Luis Potosi,Mexico,?,...,No_Alcohol_Served,not permitted,informal,completely,medium,?,familiar,f,closed,none
126,135072,22.149192,-101.002936,0101000020957F0000E7B79B1DB94758C1D29BC363D8AA...,Sushi Itto,Venustiano Carranza 1809 C Polanco,San Luis Potosi,SLP,Mexico,?,...,No_Alcohol_Served,none,informal,no_accessibility,medium,sushi-itto.com.mx,familiar,f,closed,none
127,135109,18.921785,-99.235350,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Wine-Beer,not permitted,informal,no_accessibility,medium,?,quiet,f,closed,Internet
128,135019,18.875011,-99.159422,0101000020957F0000B49B2E5C6E785AC12F9D58435241...,Restaurant Bar Coty y Pablo,Paseo de Las Fuentes 24 Pedregal de Las Fuentes,Jiutepec,Morelos,Mexico,?,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,f,closed,none
129,132877,22.135364,-100.934948,0101000020957F000090735015B84B58C1AF0DC0414698...,sirloin stockade,?,?,?,?,?,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,f,closed,none

In [3]:
id_permitido = list()

for i in df_places["placeID"]:
    id_permitido.append(i)

In [4]:
len(id_permitido)

130

In [5]:
for i in df_places["placeID"].sort_values():
    print(i)

132560
132561
132564
132572
132583
132584
132594
132608
132609
132613
132626
132630
132654
132660
132663
132665
132667
132668
132706
132715
132717
132723
132732
132733
132740
132754
132755
132766
132767
132768
132773
132825
132830
132834
132845
132846
132847
132851
132854
132856
132858
132861
132862
132866
132869
132870
132872
132875
132877
132884
132885
132921
132922
132925
132937
132951
132954
132955
132958
134975
134976
134983
134986
134987
134992
134996
134999
135000
135001
135011
135013
135016
135018
135019
135021
135025
135026
135027
135028
135030
135032
135033
135034
135035
135038
135039
135040
135041
135042
135043
135044
135045
135046
135047
135048
135049
135050
135051
135052
135053
135054
135055
135057
135058
135059
135060
135062
135063
135064
135065
135066
135069
135070
135071
135072
135073
135074
135075
135076
135079
135080
135081
135082
135085
135086
135088
135104
135106
135108
135109

In [99]:
df_accepts = df_accepts[df_accepts['placeID'].isin(id_permitido)]
df_cuisine = df_cuisine[df_cuisine['placeID'].isin(id_permitido)]
df_hours = df_hours[df_hours['placeID'].isin(id_permitido)]
df_parking = df_parking[df_parking['placeID'].isin(id_permitido)]
df_rating_final = df_rating_final[df_rating_final['placeID'].isin(id_permitido)]

In [86]:
for i in df_accepts["placeID"].sort_values():
    print(i)

132002
132002
132002
132002
132012
132012
132012
132012
132019
132019
132019
132019
132023
132023
132023
132023
132024
132024
132024
132024
132026
132026
132026
132026
132030
132030
132030
132030
132030
132031
132031
132031
132031
132031
132031
132103
132106
132106
132106
132106
132107
132107
132107
132107
132109
132109
132109
132111
132111
132111
132111
132111
132115
132116
132130
132155
132159
132159
132159
132159
132159
132160
132160
132161
132161
132163
132164
132164
132164
132165
132165
132165
132166
132177
132177
132182
132182
132182
132184
132184
132187
132187
132187
132187
132187
132187
132187
132201
132201
132204
132204
132204
132206
132206
132206
132207
132207
132211
132211
132211
132211
132212
132212
132212
132212
132213
132213
132213
132213
132215
132215
132220
132221
132228
132229
132230
132230
132230
132231
132231
132231
132231
132231
132231
132231
132232
132232
132233
132233
132237
132237
132237
132243
132243
132243
132243
132243
132243
132244
132244
132244
132244
132244
132244
132246
132275
132289
132289
132289
132289
132289
132289
132289
132289
132293
132293
132293
132296
132296
132296
132297
132297
132302
132302
132302
132302
132302
132302
132318
132318
132319
132319
132319
132319
132333
132333
132333
132336
132341
132342
132342
132343
132343
132343
132343
132344
132346
132347
132347
132347
132347
132348
132348
132353
132353
132355
132355
132355
132361
132361
132361
132364
132364
132367
132367
132367
132367
132387
132387
132392
132392
132392
132392
132396
132396
132396
132396
132396
132396
132399
132399
132399
132407
132409
132409
132409
132409
132413
132413
132413
132413
132413
132414
132414
132414
132414
132417
132419
132432
132432
132436
132436
132436
132436
132437
132437
132438
132438
132439
132439
132442
132442
132442
132443
132443
132443
132444
132444
132444
132444
132445
132446
132446
132446
132449
132458
132482
132482
132482
132483
132483
132488
132493
132493
132493
132509
132509
132509
132509
132518
132521
132521
132521
132521
132527
132527
132527
132527
132527
132530
132530
132530
132530
132531
132531
132533
132533
132535
132535
132535
132535
132537
132544
132544
132544
132544
132545
132545
132545
132545
132560
132572
132573
132573
132574
132574
132574
132575
132575
132575
132575
132576
132576
132576
132577
132577
132577
132578
132580
132581
132582
132582
132583
132583
132583
132583
132584
132585
132585
132585
132586
132587
132588
132589
132589
132589
132590
132591
132591
132591
132592
132592
132592
132592
132592
132592
132592
132593
132594
132595
132596
132597
132598
132598
132599
132600
132601
132602
132603
132604
132605
132606
132606
132607
132608
132609
132610
132611
132612
132612
132613
132614
132615
132616
132617
132617
132617
132617
132618
132619
132619
132619
132619
132619
132620
132621
132622
132623
132623
132624
132624
132624
132625
132625
132625
132625
132626
132626
132628
132629
132629
132629
132631
132635
132636
132638
132640
132642
132645
132648
132650
132653
132655
132658
132667
132671
132674
132675
132676
132677
132678
132679
132680
132681
132682
132682
132682
132682
132683
132683
132683
132684
132684
132685
132685
132685
132685
132685
132686
132686
132686
132686
132687
132687
132687
132687
132687
132688
132688
132688
132688
132688
132689
132689
132689
132689
132689
132690
132691
132691
132691
132691
132692
132692
132692
132692
132692
132693
132693
132693
132693
132694
132695
132696
132697
132697
132697
132697
132698
132699
132699
132699
132700
132700
132700
132700
132701
132702
132703
132704
132705
132706
132706
132707
132708
132709
132710
132711
132712
132713
132714
132715
132716
132717
132718
132719
132720
132720
132720
132720
132720
132721
132722
132723
132723
132724
132724
132724
132724
132724
132725
132726
132726
132726
132726
132727
132728
132730
132731
132732
132733
132733
132733
132733
132734
132734
132734
132734
132735
132735
132735
132735
132736
132736
132736
132736
132737
132738
132739
132740
132741
132742
132743
132744
132745
132746
132747
132747
132747
132747
132747
132748
132749
132750
132750
132751
132751
132752
132753
132754
132755
132755
132755
132755
132756
132756
132756
132756
132756
132757
132758
132759
132760
132760
132761
132761
132761
132762
132763
132764
132765
132766
132767
132767
132767
132768
132768
132769
132770
132771
132771
132772
132773
132774
132774
132774
132775
132776
132776
132776
132777
132777
132777
132777
132778
132779
132779
132780
132781
132781
132782
132782
132782
132783
132783
132783
132783
132783
132784
132784
132784
132784
132784
132785
132785
132785
132786
132786
132786
132786
132787
132787
132787
132787
132788
132788
132788
132789
132789
132789
132789
132790
132790
132790
132790
132790
132791
132791
132791
132791
132791
132792
132792
132792
132792
132793
132793
132793
132793
132793
132794
132795
132795
132795
132796
132796
132796
132796
132797
132797
132798
132799
132799
132799
132801
132801
132802
132802
132802
132803
132804
132804
132804
132804
132805
132806
132806
132806
132806
132807
132807
132807
132808
132808
132808
132809
132810
132811
132811
132811
132815
132817
132819
132820
132820
132821
132824
132824
132825
132826
132826
132826
132826
132827
132828
132829
132834
132835
132835
132835
132835
132835
132836
132837
132840
132841
132842
132843
132845
132846
132847
132848
132849
132850
132851
132852
132853
132854
132854
132854
132855
132856
132857
132857
132857
132858
132859
132859
132859
132859
132859
132860
132860
132860
132860
132860
132861
132861
132861
132861
132861
132862
132862
132862
132862
132862
132863
132863
132863
132863
132863
132864
132865
132866
132867
132868
132869
132870
132871
132872
132872
132873
132873
132873
132873
132873
132875
132875
132875
132875
132875
132880
132880
132880
132880
132880
132885
132886
132886
132886
132886
132887
132887
132887
132887
132888
132888
132888
132889
132890
132891
132892
132892
132893
132894
132895
132896
132897
132899
132900
132900
132900
132900
132900
132901
132902
132903
132904
132907
132908
132909
132910
132911
132912
132913
132914
132915
132916
132917
132917
132917
132917
132917
132918
132919
132920
132921
132922
132923
132924
132925
132926
132927
132927
132927
132927
132927
132928
132929
132930
132931
132931
132931
132931
132931
132932
132933
132934
132935
132936
132937
132938
132939
132940
132941
132942
132944
132945
132946
132947
132947
132948
132950
132951
132953
132953
132953
132953
132954
132954
132954
132954
132955
132955
132955
132955
132955
132956
132956
132956
132956
132957
132957
132957
132957
132958
132958
132958
132958
132958
132959
132960
132961
132962
132963
132964
132965
132966
132967
132968
132969
132970
132971
132972
132973
132974
132975
132976
132977
132978
132979
132980
132981
132982
132983
132984
132985
132986
132993
132994
132995
132996
133007
133008
133009
133014
133020
133026
133026
133027
133027
133027
133028
133029
133030
133030
133030
133031
133032
133033
133033
133033
133033
133034
133035
133036
133037
133038
133043
133043
133043
133043
133047
133048
133049
134970
134970
134970
134970
134971
134971
134971
134972
134972
134972
134973
134973
134973
134974
134974
134974
134975
134975
134975
134975
134976
134976
134976
134976
134977
134977
134977
134978
134978
134978
134980
134981
134982
134983
134983
134983
134984
134984
134984
134985
134985
134985
134987
134988
134988
134988
134989
134989
134989
134989
134990
134991
134991
134991
134991
134992
134992
134992
134993
134993
134993
134993
134994
134994
134994
134995
134996
134998
135000
135001
135001
135001
135001
135002
135002
135002
135003
135004
135004
135004
135005
135006
135006
135006
135006
135007
135007
135007
135008
135008
135008
135008
135009
135010
135011
135012
135013
135014
135015
135016
135017
135018
135018
135018
135018
135021
135022
135023
135024
135024
135024
135024
135025
135025
135025
135025
135027
135027
135027
135027
135028
135028
135028
135028
135029
135029
135029
135029
135030
135031
135031
135031
135032
135032
135032
135033
135033
135033
135033
135034
135034
135034
135034
135035
135035
135035
135035
135036
135037
135037
135037
135038
135039
135040
135040
135040
135041
135042
135043
135044
135045
135045
135045
135045
135046
135046
135046
135047
135047
135047
135048
135048
135048
135048
135049
135050
135050
135050
135050
135051
135052
135052
135052
135053
135053
135053
135053
135054
135054
135054
135055
135055
135055
135055
135056
135057
135057
135057
135057
135058
135058
135058
135059
135060
135061
135061
135061
135061
135062
135063
135064
135064
135064
135065
135065
135065
135065
135066
135066
135066
135067
135067
135067
135068
135068
135068
135069
135070
135071
135071
135071
135071
135072
135072
135072
135072
135073
135073
135073
135074
135074
135074
135075
135076
135076
135076
135076
135077
135078
135078
135078
135079
135079
135080
135080
135080
135080
135081
135081
135081
135082
135084
135084
135084
135085
135086
135086
135086
135088
135089
135089
135089
135089
135090
135091
135091
135091
135092
135093
135093
135094
135097
135097
135097
135097
135098
135098
135098
135098
135099
135099
135099
135100
135101
135102
135102
135102
135102
135103
135103
135103
135104
135104
135104
135105
135106
135106
135106
135107
135107
135107
135107
135107
135109
135110
135110
135110
135110
135110

In [15]:
df_cuisine

     placeID        Rcuisine
0     135110         Spanish
1     135109         Italian
2     135107  Latin_American
3     135106         Mexican
4     135105       Fast_Food
..       ...             ...
911   132005         Seafood
912   132004         Seafood
913   132003   International
914   132002         Seafood
915   132001   Dutch-Belgian

[916 rows x 2 columns]

In [17]:
df_hours

      placeID         hours                  days
0      135111  00:00-23:30;  Mon;Tue;Wed;Thu;Fri;
1      135111  00:00-23:30;                  Sat;
2      135111  00:00-23:30;                  Sun;
3      135110  08:00-19:00;  Mon;Tue;Wed;Thu;Fri;
4      135110  00:00-00:00;                  Sat;
...       ...           ...                   ...
2334   132012  12:00-22:00;                  Sun;
2335   132012  12:00-22:00;  Mon;Tue;Wed;Thu;Fri;
2336   132012  12:00-22:00;  Mon;Tue;Wed;Thu;Fri;
2337   132012  12:00-22:00;                  Sat;
2338   132012  12:00-22:00;                  Sat;

[2339 rows x 3 columns]

In [19]:
df_parking

     placeID parking_lot
0     135111      public
1     135110        none
2     135109        none
3     135108        none
4     135107        none
..       ...         ...
697   132024      street
698   132023         fee
699   132023      public
700   132012      public
701   132012      street

[702 rows x 2 columns]

In [98]:
df_rating_final

      placeID  rating  food_rating  service_rating
0      135085       2            2               2
1      135038       2            2               1
2      132825       2            2               2
3      135060       1            2               2
4      135104       1            1               2
...       ...     ...          ...             ...
1156   132630       1            1               1
1157   132715       1            1               0
1158   132733       1            1               0
1159   132594       1            1               1
1160   132660       0            0               0

[1161 rows x 4 columns]

#### INSERTAR TABLAS EN SQL

In [6]:
# ESTABLECER CONEXIÃN CON LA BASE DE DATOS DE MYSQL
# PARA GUARDAR LA CONEXIÃN Y EL CURSOR, HAY QUE IGUALAR LA FUNCIÃN A DOS VARIABLES
def conexion():
    db = mysql.connector.connect(host     = "localhost", # donde se aloja la base de datos
                             user     = "", # poned vuestro usuario
                             password = "", # poned vuestra contraseÃ±a
                             database = None)
    cursor = db.cursor()
    return db, cursor

# CERRAR LA CONEXIÃN
def cerrar_conexion(cursor, db):
    cursor.fetchall() # se utiliza para recuperar todas las filas del conjunto de resultados despuÃ©s de ejecutar una consulta en una base de datos. Esto es Ãºtil cuando deseas trabajar con los resultados de una consulta en tu programa Python
    cursor.close()
    db.close()

# CREAR UNA BASE DE DATOS DANDOLE EL NOMBRE DE LA BASE DE DATOS
def crear_database(database):
    db, cursor = conexion()
    cursor.execute(f"CREATE DATABASE IF NOT EXISTS {database};")
    cerrar_conexion(cursor, db)

# CREAR UNA TABLA EN UNA BASE DE DATOS.
# PASANDOLE LA BASE DE DATOS DONDE QUEREMOS CREARLA Y LA QUERY DE LA TABLA QUE QUEREMOS CREAR
def crear_tablas(query, database):
    db, cursor = conexion()
    query_database = f"USE {database};"
    cursor.execute(query_database)
    cursor.execute(query)
    cerrar_conexion(cursor, db)

# EJECUTAR QUERYS DE CONSULTAS:
def ejecutar_consulta(database, query):
    db, cursor = conexion()
    cursor.execute(f"USE {database};")

    # Ejecutar la consulta
    cursor.execute(query)
    # Obtener los resultados, si es una consulta SELECT
    resultados = cursor.fetchall()
    # Hacer commit para guardar los cambios (en caso de INSERT, UPDATE, DELETE, etc.)
    db.commit()
    # Cerrar la conexiÃ³n
    cerrar_conexion(cursor, db)
    return resultados

In [7]:
def conexion():
    db = mysql.connector.connect(host     = "localhost", # donde se aloja la base de datos
                             user     = "root", # poned vuestro usuario
                             password = "EZTR934P", # poned vuestra contraseÃ±a
                             database = None)
    cursor = db.cursor()
    return db, cursor

#### Crear database

In [8]:
import mysql.connector

In [39]:
crear_database("Restaurantes")

#### Crear tablas

In [26]:
df_places.columns

Index(['placeID', 'latitude', 'longitude', 'the_geom_meter', 'name', 'address',
       'city', 'state', 'country', 'fax', 'zip', 'alcohol', 'smoking_area',
       'dress_code', 'accessibility', 'price', 'url', 'Rambience', 'franchise',
       'area', 'other_services'],
      dtype='object')

### DF PLACES

In [27]:
df_places.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   placeID         130 non-null    int64
 1   latitude        130 non-null    float64
 2   longitude       130 non-null    float64
 3   the_geom_meter  130 non-null    object
 4   name            130 non-null    object
 5   address         130 non-null    object
 6   city            130 non-null    object
 7   state           130 non-null    object
 8   country         130 non-null    object
 9   fax             130 non-null    object
 10  zip             130 non-null    object
 11  alcohol         130 non-null    object
 12  smoking_area    130 non-null    object
 13  dress_code      130 non-null    object
 14  accessibility   130 non-null    object
 15  price           130 non-null    object
 16  url             130 non-null    object
 17  Rambience       130 non-null    object
 18  franchise       130 non-null    object
 19  area            130 non-null    object
 20  other_services  130 non-null    object
dtypes: float64(2), int64(1), object(18)
memory usage: 21.5+ KB

In [76]:
query_geoplaces = """CREATE TABLE IF NOT EXISTS geoplaces (
                placeID INT UNSIGNED AUTO_INCREMENT NOT NULL,
                latitude FLOAT,
                longitude FLOAT,
                the_geom_meter VARCHAR(250),
                name VARCHAR(250),
                address VARCHAR(250),
                city VARCHAR(250),
                state VARCHAR(250),
                country VARCHAR(250),
                fax VARCHAR(250),
                zip VARCHAR(250),
                alcohol VARCHAR (250),
                smoking_area VARCHAR(250),
                dress_code VARCHAR(250),
                accessibility VARCHAR(250),
                price VARCHAR(250),
                url VARCHAR(250),
                Rambience VARCHAR(250),
                franchise VARCHAR(250),
                area VARCHAR(250),
                other_services VARCHAR(250),
                PRIMARY KEY (placeID)
                );"""

In [77]:
crear_tablas(query_geoplaces, "Restaurantes")

### DF ACCEPTS

In [54]:
df_accepts.columns

Index(['placeID', 'Rpayment'], dtype='object')

In [55]:
df_accepts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1314 entries, 0 to 1313
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   placeID   1314 non-null   int64
 1   Rpayment  1314 non-null   object
dtypes: int64(1), object(1)
memory usage: 20.7+ KB

In [108]:
query_accepts = """CREATE TABLE IF NOT EXISTS pagos (
                placeID INT UNSIGNED,
                Rpayment VARCHAR(250),
                FOREIGN KEY (placeID) REFERENCES geoplaces (placeID)
                );"""

In [109]:
crear_tablas(query_accepts, "Restaurantes")

### DF CUISINE

In [74]:
df_cuisine

     placeID        Rcuisine
0     135110         Spanish
1     135109         Italian
2     135107  Latin_American
3     135106         Mexican
4     135105       Fast_Food
..       ...             ...
911   132005         Seafood
912   132004         Seafood
913   132003   International
914   132002         Seafood
915   132001   Dutch-Belgian

[916 rows x 2 columns]

In [75]:
df_cuisine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 916 entries, 0 to 915
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   placeID   916 non-null    int64
 1   Rcuisine  916 non-null    object
dtypes: int64(1), object(1)
memory usage: 14.4+ KB

In [111]:
query_cuisine =  """CREATE TABLE IF NOT EXISTS cuisine (
                placeID INT UNSIGNED,
                Rcuisine VARCHAR(250),
                FOREIGN KEY (placeID) REFERENCES geoplaces (placeID)
                );"""

In [113]:
crear_tablas(query_cuisine, "Restaurantes")

### DF HOURS

In [115]:
df_hours.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 384 entries, 6 to 1796
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   placeID  384 non-null    int64
 1   hours    384 non-null    object
 2   days     384 non-null    object
dtypes: int64(1), object(2)
memory usage: 12.0+ KB

In [117]:
query_hours =  """CREATE TABLE IF NOT EXISTS hours (
                placeID INT UNSIGNED,
                hours VARCHAR(250),
                days VARCHAR(250),
                FOREIGN KEY (placeID) REFERENCES geoplaces (placeID)
                );"""

In [119]:
crear_tablas(query_hours, "Restaurantes")

### DF PARKING

In [121]:
df_parking.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 130 entries, 2 to 614
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   placeID      130 non-null    int64
 1   parking_lot  130 non-null    object
dtypes: int64(1), object(1)
memory usage: 3.0+ KB

In [141]:
query_parking =  """CREATE TABLE IF NOT EXISTS parking (
                placeID INT UNSIGNED,
                parking_lot VARCHAR(250),
                FOREIGN KEY (placeID) REFERENCES geoplaces (placeID)
                );"""

In [142]:
crear_tablas(query_parking, "Restaurantes")

### DF RATING_FINAL

In [128]:
df_rating_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1161 entries, 0 to 1160
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   placeID         1161 non-null   int64
 1   rating          1161 non-null   int64
 2   food_rating     1161 non-null   int64
 3   service_rating  1161 non-null   int64
dtypes: int64(4)
memory usage: 45.4 KB

In [130]:
query_rating =  """CREATE TABLE IF NOT EXISTS rating (
                placeID INT UNSIGNED,
                rating INT,
                food_rating INT,
                service_rating INT,
                FOREIGN KEY (placeID) REFERENCES geoplaces (placeID)
                );"""

In [132]:
crear_tablas(query_rating, "Restaurantes")

## INTRODUCIMOS LOS DATOS

In [134]:
def insertar_datos_porfila(df, database, tabla):
    db, cursor = conexion()
    cursor.execute(f"USE {database};")

    # Iterar sobre las filas del DataFrame e insertar cada fila en la tabla
    for _, fila in df.iterrows(): #Este mÃ©todo de pandas retorna un generador que produce pares (Ã­ndice, fila) para cada fila del DataFrame df. 
                                  #el guion bajo _ se utiliza para descartar el Ã­ndice, ya que no se estÃ¡ utilizando dentro del bucle.
                                  #AquÃ­ el isinstance verifica que le valor es un str, sino lo convierte a str ya que la query tiene que ser str
        valores = ", ".join([f"'{valor}'" if isinstance(valor, str) else str(valor) for valor in fila])
        query = f"INSERT INTO {tabla} VALUES ({valores});"
        cursor.execute(query)

    # Hacer commit para guardar los cambios
    db.commit()
    cerrar_conexion(cursor, db)

In [135]:
insertar_datos_porfila(df_places, "Restaurantes", "geoplaces")

In [136]:
insertar_datos_porfila(df_accepts, "Restaurantes", "pagos")

In [138]:
insertar_datos_porfila(df_cuisine, "Restaurantes", "cuisine")

In [140]:
insertar_datos_porfila(df_hours, "Restaurantes", "hours")

In [144]:
insertar_datos_porfila(df_parking, "Restaurantes", "parking")

In [146]:
insertar_datos_porfila(df_rating_final, "Restaurantes", "rating")

### SACAR DATAFRAME

In [9]:
def execute_queryReturnDF(query, database, host = "localhost", user = "root", password = "EZTR934P")->pd.DataFrame:
    
    db = mysql.connector.connect(host     = host,
                                 user     = user,
                                 password = "EZTR934P",
                                 database = "Restaurantes")

    cursor = db.cursor()

    cursor.execute(query)
    column_names = cursor.column_names
    result=cursor.fetchall()
    cursor.fetchall() # Vaciamos el cursor
    cursor.close()
    db.close()
    return pd.DataFrame(data=result,columns=column_names)

In [10]:
query_database = """
SELECT
*
FROM
geoplaces
JOIN
pagos ON geoplaces.placeID=pagos.placeID
JOIN
cuisine ON geoplaces.placeID=cuisine.placeID
JOIN
hours ON geoplaces.placeID=hours.placeID
JOIN
parking ON geoplaces.placeID=parking.placeID
JOIN
rating ON geoplaces.placeID=rating.placeID
ORDER BY
geoplaces.placeID;
"""

In [11]:
df = execute_queryReturnDF(query_database, database = "Restaurantes")

In [12]:
df_no_duplicados = df.drop_duplicates()

In [13]:
# Eliminar columnas duplicadas
df_2 = df_no_duplicados.loc[:,~df_no_duplicados.columns.duplicated()]

## RECOMENDADOR

In [14]:
df_2

,placeID,latitude,longitude,the_geom_meter,name,address,city,state,country,fax,...,area,other_services,Rpayment,Rcuisine,hours,days,parking_lot,rating,food_rating,service_rating
0,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,open,none,cash,Regional,08:00-12:00;,Mon;Tue;Wed;Thu;Fri;,public,1,0,0
1,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,open,none,cash,Regional,08:00-12:00;,Mon;Tue;Wed;Thu;Fri;,public,0,0,0
2,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,open,none,cash,Regional,08:00-12:00;,Mon;Tue;Wed;Thu;Fri;,public,0,2,0
3,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,open,none,cash,Regional,08:00-12:00;,Mon;Tue;Wed;Thu;Fri;,public,1,2,1
8,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,open,none,cash,Regional,00:00-00:00;,Sat;,public,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100235,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,closed,Internet,cash,Italian,08:00-21:00;,Sat;,none,1,2,1
100240,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,closed,Internet,cash,Italian,08:00-21:00;,Sun;,none,0,0,0
100241,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,closed,Internet,cash,Italian,08:00-21:00;,Sun;,none,2,2,1
100242,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,closed,Internet,cash,Italian,08:00-21:00;,Sun;,none,1,1,1
100243,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,closed,Internet,cash,Italian,08:00-21:00;,Sun;,none,1,2,1

In [15]:
# vamos a hacer columnas de los dÃ­as con sus respectivas horas

df_2["Mon;Tue;Wed;Thu;Fri;"] = df_2[(df_2["days"] == "Mon;Tue;Wed;Thu;Fri;")]["hours"]
df_2["Sat;"] = df_2[(df_2["days"] == "Sat;")]["hours"]
df_2["Sun;"] = df_2[(df_2["days"] == "Sun;")]["hours"]

In [16]:
# Ejemplo de usuario [nombre place y puntuaciÃ³n]

data = [["puesto de gorditas", 1],
         ["Paniroles", 1],
         ["Pollo_Frito_Buenos_Aires", 0]
       ]

data_user_1 = pd.DataFrame(data = data, columns = ["name", "rating"])

In [17]:
# Vamos a hacer un df comparador

df_buscador = pd.DataFrame()

for restaurante in data_user_1["name"]:
    df_buscador = pd.concat([df_buscador, df_2[df_2["name"] == restaurante]])

In [18]:
df_busqueda = pd.DataFrame()
for restaurante in data_user_1.name:
    df_busqueda = pd.concat([df_busqueda, df_2[(df_2["name"] == restaurante)]], ignore_index=True)

In [19]:
df_busqueda

,placeID,latitude,longitude,the_geom_meter,name,address,city,state,country,fax,...,Rcuisine,hours,days,parking_lot,rating,food_rating,service_rating,Mon;Tue;Wed;Thu;Fri;,Sat;,Sun;
0,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,08:00-12:00;,Mon;Tue;Wed;Thu;Fri;,public,1,0,0,08:00-12:00;,NaN,NaN
1,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,08:00-12:00;,Mon;Tue;Wed;Thu;Fri;,public,0,0,0,08:00-12:00;,NaN,NaN
2,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,08:00-12:00;,Mon;Tue;Wed;Thu;Fri;,public,0,2,0,08:00-12:00;,NaN,NaN
3,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,08:00-12:00;,Mon;Tue;Wed;Thu;Fri;,public,1,2,1,08:00-12:00;,NaN,NaN
4,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,00:00-00:00;,Sat;,public,1,0,0,NaN,00:00-00:00;,NaN
5,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,00:00-00:00;,Sat;,public,0,0,0,NaN,00:00-00:00;,NaN
6,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,00:00-00:00;,Sat;,public,0,2,0,NaN,00:00-00:00;,NaN
7,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,00:00-00:00;,Sat;,public,1,2,1,NaN,00:00-00:00;,NaN
8,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,00:00-00:00;,Sun;,public,1,0,0,NaN,NaN,00:00-00:00;
9,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,00:00-00:00;,Sun;,public,0,0,0,NaN,NaN,00:00-00:00;
10,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,00:00-00:00;,Sun;,public,0,2,0,NaN,NaN,00:00-00:00;
11,132560,23.7523,-99.1669,0101000020957F0000FC60BDA8E88157C1B2C357D6DA4E...,puesto de gorditas,frente al tecnologico,victoria,tamaulipas,mexico,?,...,Regional,00:00-00:00;,Sun;,public,1,2,1,NaN,NaN,00:00-00:00;
12,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Mon;Tue;Wed;Thu;Fri;,none,0,0,0,08:00-21:00;,NaN,NaN
13,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Mon;Tue;Wed;Thu;Fri;,none,2,2,1,08:00-21:00;,NaN,NaN
14,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Mon;Tue;Wed;Thu;Fri;,none,1,1,1,08:00-21:00;,NaN,NaN
15,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Mon;Tue;Wed;Thu;Fri;,none,1,2,1,08:00-21:00;,NaN,NaN
16,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Sat;,none,0,0,0,NaN,08:00-21:00;,NaN
17,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Sat;,none,2,2,1,NaN,08:00-21:00;,NaN
18,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Sat;,none,1,1,1,NaN,08:00-21:00;,NaN
19,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Sat;,none,1,2,1,NaN,08:00-21:00;,NaN
20,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Sun;,none,0,0,0,NaN,NaN,08:00-21:00;
21,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Sun;,none,2,2,1,NaN,NaN,08:00-21:00;
22,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Sun;,none,1,1,1,NaN,NaN,08:00-21:00;
23,135109,18.9218,-99.2354,0101000020957F0000A6BF695F136F5AC1DADF87B20556...,Paniroles,?,?,?,?,?,...,Italian,08:00-21:00;,Sun;,none,1,2,1,NaN,NaN,08:00-21:00;
24,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,12:00-18:00;,Mon;Tue;Wed;Thu;Fri;,yes,1,1,1,12:00-18:00;,NaN,NaN
25,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,12:00-18:00;,Mon;Tue;Wed;Thu;Fri;,yes,0,0,0,12:00-18:00;,NaN,NaN
26,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,12:00-18:00;,Mon;Tue;Wed;Thu;Fri;,yes,1,0,1,12:00-18:00;,NaN,NaN
27,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,12:00-18:00;,Mon;Tue;Wed;Thu;Fri;,yes,1,2,1,12:00-18:00;,NaN,NaN
28,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,10:00-18:00;,Sat;,yes,1,1,1,NaN,10:00-18:00;,NaN
29,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,10:00-18:00;,Sat;,yes,0,0,0,NaN,10:00-18:00;,NaN
30,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,10:00-18:00;,Sat;,yes,1,0,1,NaN,10:00-18:00;,NaN
31,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,10:00-18:00;,Sat;,yes,1,2,1,NaN,10:00-18:00;,NaN
32,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,00:00-23:30;,Sun;,yes,1,1,1,NaN,NaN,00:00-23:30;
33,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,00:00-23:30;,Sun;,yes,0,0,0,NaN,NaN,00:00-23:30;
34,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,00:00-23:30;,Sun;,yes,1,0,1,NaN,NaN,00:00-23:30;
35,132609,23.7603,-99.1659,0101000020957F0000A478418BBA8057C133851EB22C4E...,Pollo_Frito_Buenos_Aires,tampico,victoria,Tamaulipas,Mexico,?,...,Fast_Food,00:00-23:30;,Sun;,yes,1,2,1,NaN,NaN,00:00-23:30;